import 'package:astro_info/models/object.dart';

final List<Object> objectList = [
const Object(
  name: "Merkur",
  photo: "images/planets/merkur.png",
  subtitle: "Stone planet of our Solar System",
  category: Category.planet,
  content: "This is merkur",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),
const Object(
  name: "Venus",
  photo: "images/planets/venus.png",
  subtitle: "Hot planet of our Solar System",
  category: Category.planet,
  content: "This is Venus",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),
const Object(
  name: "Earth",
  photo: "images/planets/earth.png",
  subtitle: "Our Home",
  category: Category.planet,
  content: "This is Earth",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),
const Object(
  name: "Mars",
  photo: "images/planets/mars.png",
  subtitle: "Red planet of our Solar System",
  category: Category.planet,
  content: "This is Mars",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),
const Object(
  name: "Jupiter",
  photo: "images/planets/jupiter.png",
  subtitle: "Gas Giant",
  category: Category.planet,
  content: "This is Jupiter",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),
const Object(
  name: "Saturn",
  photo: "images/planets/saturn.png",
  subtitle: "Planet with Ring",
  category: Category.planet,
  content: "This is Saturn",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),
const Object(
  name: "Uranus",
  photo: "images/planets/uranus.png",
  subtitle: "Blue Gas Giant",
  category: Category.planet,
  content: "This is Uranus",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),
const Object(
  name: "Neptune",
  photo: "images/planets/neptune.png",
  subtitle: "Out Gas Giant",
  category: Category.planet,
  content: "This is Naptune",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),
const Object(
  name: "Sun",
  photo: "images/planets/sun.png",
  subtitle: "Our Sun",
  category: Category.star,
  content: "This is Sun",
  numberOfSatellites: 2,
  mass: 2.22,
  surfaceArea: 2.55,
  radius: 34.4,
  temperature: 56.33,
),

]; 